define([], function () {
  return {
    "AzureFunctionUrlFieldDescription": "The url to trigger the azure function used to process requests",
    "AzureFunctionUrlFieldLabel": "Azure Function Url",
    "SitePropCommentsOnSitePagesDisabled": "Comments on Site Pages",
    "SitePropContainsAppCatalog": "App Catalog",
    "SitePropCreated": "Date Created",
    "SitePropCustomScriptsEnabled": "Custom Scripts",
    "SitePropDisableCompanyWideSharingLinks": "Company Wide Sharing Links",
    "SitePropHubSite": "Hub Site",
    "SitePropHubSiteConnected": "Connected Hub Site",
    "SitePropIncreaseStorage": "Increase Site Storage",
    "SitePropLockState": "Lock State",
    "SitePropShareByEmailEnabled": "Shared By Email",
    "SitePropSocialBarOnSitePagesDisabled": "Social Bar on Site Pages",
    "SitePropStorageUsed": "Storage Used",
    "SitePropTemplate": "Site Template",
    "SitePropTitle": "Site Title",
    "WebPropCommentsOnSitePagesDisabled": "Comments on Site Pages",
    "WebPropSearchPropertyKey": "Key",
    "WebPropSearchPropertyDescription": "Description",
    "WebPropSearchPropertyLabel": "Label",
    "WebPropSearchPropertyTabName": "Tab Name",
    "WebPropSearchPropertyValues": "Values",
    "WebPropExcludeFromOfflineClient": "Exclude From Offline Client",
    "WebPropSearchScope": "Search Scope",
    "WebPropTemplate": "Web Template",
    "WebPropTitle": "Web Title",
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Group Name",
    "DescriptionFieldLabel": "Description Field",
    "AppLocalEnvironmentSharePoint": "The app is running on your local environment as SharePoint web part",
    "AppLocalEnvironmentTeams": "The app is running on your local environment as Microsoft Teams app",
    "AppLocalEnvironmentOffice": "The app is running on your local environment in office.com",
    "AppLocalEnvironmentOutlook": "The app is running on your local environment in Outlook",
    "AppSharePointEnvironment": "The app is running on SharePoint page",
    "AppTeamsTabEnvironment": "The app is running in Microsoft Teams",
    "AppOfficeEnvironment": "The app is running in office.com",
    "AppOutlookEnvironment": "The app is running in Outlook",
    "UnknownEnvironment": "The app is running in an unknown environment"
  }
});