define([], function () {
  return {
    "AzureFunctionUrlFieldDescription": "The url to trigger the azure function used to process requests",
    "AzureFunctionUrlFieldLabel": "Azure Function Url",
    "SitePropCommentsOnSitePagesDisabled": "Comments on Site Pages",
    "SitePropContainsAppCatalog": "App Catalog",
    "SitePropContainsAppCatalogUrl": "App Catalog Azure Function",
    "SitePropDisableCompanyWideSharingLinks": "Company Wide Sharing Links",
    "SitePropShareByEmailEnabled": "Shared By Email",
    "SitePropSocialBarOnSitePagesDisabled": "Social Bar on Site Pages",
    "WebPropCommentsOnSitePagesDisabled": "Comments on Site Pages",
    "WebPropSearchPropertyName": "DesignatedMAJCOM",
    "WebPropSearchPropertyDescription": "Search Property Description",
    "WebPropSearchPropertyLabel": "Search Property Label",
    "WebPropExcludeFromOfflineClient": "Exclude From Offline Client",
    "WebPropSearchScope": "Search Scope",
    "WebPropWebTemplate": "Web Template",
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Group Name",
    "DescriptionFieldLabel": "Description Field",
    "AppLocalEnvironmentSharePoint": "The app is running on your local environment as SharePoint web part",
    "AppLocalEnvironmentTeams": "The app is running on your local environment as Microsoft Teams app",
    "AppLocalEnvironmentOffice": "The app is running on your local environment in office.com",
    "AppLocalEnvironmentOutlook": "The app is running on your local environment in Outlook",
    "AppSharePointEnvironment": "The app is running on SharePoint page",
    "AppTeamsTabEnvironment": "The app is running in Microsoft Teams",
    "AppOfficeEnvironment": "The app is running in office.com",
    "AppOutlookEnvironment": "The app is running in Outlook",
    "UnknownEnvironment": "The app is running in an unknown environment"
  }
});